### ISSUE TITLE
Autocomplete Mentions -  Enter sends chat message and doesn't just autocomplete

### ISSUE THREAD

**Issue by coryshaw1** [DubPlus/DubPlus#12] opened 2017-02-24 14:09 UTC
Not sure if we planned on overriding user autocomplete styles again for Dub+ autocomplete styles. We only use our autocomplete style for emotes now, and if autocomplete emotes is active, it breaks selection of Dubtrack's user mention autocomplete. Even deselecting the option, doesn't fix binding of enter (keyCode: 13)

**Comment by coryshaw1** [comment] 2017-02-27 14:00
The mention autocomplete seems to be working as intended now, but the emoji autocomplete is reported as broken. Attempting to autocomplete an emoji actually deletes the text.

**Comment by FranciscoG** [comment] 2017-03-03 18:32
can you do a screen video capture of the issue?  I am not able to replicate any issues on my end so I'm probably not taking the right steps to reproduce this.   I've tried many ways and it all works fine for me

**Comment by coryshaw1** [comment] 2017-03-03 18:35
1. Turn on Emotes
2. Type ':' and begin to start any emote
3. Press enter and your text disappears and doesn't autocomplete

**Comment by FranciscoG** [comment] 2017-03-03 18:37
see that doesnt happen to me.  When I press enter it selects it and adds it to the input

**Comment by coryshaw1** [comment] 2017-03-03 18:38
![autocomplete](http://i.imgur.com/sFRyVSL.gif)

**Comment by FranciscoG** [comment] 2017-03-03 22:48
pull request #20 should fix this when it gets merged

**Comment by FranciscoG** [comment] 2018-01-11 19:19
this still happening?

**Comment by FranciscoG** [comment] 2019-10-15 22:16
2.0.0 completely rewrote the auto complete system and simplified it

Might be buggy but in a different way lol

So I tried mimicking the way that dubtrack does the user autocomplete.  Still not perfect but better.

**Comment by FranciscoG** [comment] 2019-10-25 18:06
closing this.  Any new issues with autocomplete should be a new bug since it's a new code base and rewrite

**Closed by FranciscoG** 2019-10-25 18:06 UTC
Labels: bug
